export interface ContactoType {
    Acepta_Envio_Informacion: string
    Apellido: string
    Calle: string
    Codigo_Postal: string
    Conexion: string
    Conflictivo: string
    Correo_electronico_no_valido: string
    Correo_E_alternativo_1: string
    Correo_E_alternativo_2: string
    Departamento: string
    Direccion_de_correo_electronico: string
    DNI: string
    Fecha_Alta: string
    Fecha_de_creacion: Date
    Fecha_de_ultima_actualizacion: string
    Fecha_Rechazo_Op: string
    ID_de_contacto: string
    ID_de_usuario: string
    ID_en_AIS: string
    Id_en_BI: string
    Localidad: string
    Marca_ADS: string
    No_Molestar: string
    Nombre: string
    Nombre_completo: string
    Numero_de_domicilio: string
    Pais: string
    Piso: string
    Poliza_Vida: string
    Poliza_Vida_2: string
    Poliza_Vida_3: string
    Poliza_Vida_4: string
    Provincia: string
    Telefono_de_la_oficina_sin_formato: string
    Telefono_de_oficina: string
    Telefono_del_asistente: string
    Telefono_del_asistente_sin_formato: string
    Telefono_movil: string
    Telefono_movil_sin_formato: string
    Telefono_particular: string
    Telefono_particular_sin_formato: string
    Tipo_Documento: string
    Vendedor: string
}