export { Archivo } from './Archivo'
export type { IArchivo } from './Archivo'
export { Contacto } from './Contacto'
export type { IContacto } from './Contacto'
export { Incidente } from './Incidente'
export type { IIncidente } from './Incidente'
export { LogActividad } from './LogActividad'
export type { ILogActividad } from './LogActividad'
export { NotaPrivada } from './NotaPrivada'
export type { INotaPrivada } from './NotaPrivada'
export { Organizacion } from './Organizacion'
export type { IOrganizacion } from './Organizacion'
export { Poliza } from './Poliza'
export type { IPoliza } from './Poliza'
export { Productor } from './Productor'
export type { IProductor } from './Productor'
export { Respuesta } from './Respuesta'
export type { IRespuesta } from './Respuesta'
export { Riesgo } from './Riesgo'
export type { IRiesgo } from './Riesgo'
export { Siniestro } from './Siniestro'
export type { ISiniestro } from './Siniestro'
export { Tarea } from './Tarea'
export type { ITarea } from './Tarea'
export { TipoIncidente } from './TipoIncidente'
export type { ITipoIncidente } from './TipoIncidente'
